version: '3.1'

services:

  db_postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5432:5432
